version: '3.8'

services:

  web:
    build: ./src
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./src:/usr/src/app
    ports:
      - 8002:8000
    environment:
      - REAL_DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/real_db
      - TEST_DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/test_db
    depends_on:
      - db

  db:
    image: postgres:15.3
#    expose:
#      - 5432
    ports:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
